### ISSUE TITLE
Cannot cancel Data Export

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#36]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>I accidentally started an export of 194111 records because Save UUIDs does all in the results not just the highlighted. It would not let me pause or cancel the job.
<strong>Instance HRID: </strong>``
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Data export
<strong>Urgency: </strong>I need help soon.
<strong>Browser: </strong>Chrome

**Comment by ahafele** [comment]
@jlkalchik resolved now

**Comment by michelleif** [comment]
can we close this

**Comment by michelleif** [comment]
spoke with Jeanette, is still an issue, but on FOLIO side.
you cannot cancel an export the same way you can with data import. 
it will just be a drain on the system resources if people try to export too large a file during working hours and can't stop/pause it

there is an issue in community for adding a pause feature to exports, we are putting this issue on our watchlist https://issues.folio.org/browse/UXPROD-4309
